swagger: '2.0'
info:
  title: Signhost api
  description: Integrate with signhost using our API to create transactions and retrieve current status. 
  version: 1.0
produces:
  - application/json
parameters:
  - name: Application
    description: The APPKey
    in: header
    type: string
    required: true
paths:
  '/api/transaction/{transactionId}':
    get:
      description: Returns current transaction details
      parameters:
        - name: transactionId
          description: ID of the transaction
          in: path
          required: true
      responses:
        '200':
          description: Details of the transaction
          schema:
            title: Transaction
            type: object
            properties:
              Id:
                type: string
              CreatedDate:
                type: dateTime
        '401':
          description: Not authorized to access the specified transaction

  '/api/transaction':
    post:
      description: Creates a new transaction
      parameters:
        - in: body
          name: body
          description: Transaction to be added
          required: true
          schema:
            type: object
            properties:
              File:
                type: object
                properties:
                  Name:
                    type: string
                    description: The name of the file
              Seal:
                type: boolean
                default: true
                description: Seal the document before sending to the signers.
              Signers:
                type: array
                items:
                  type: object
                  properties:
                    Email:
                      type: string
                      required: true
                      description: The e-mail address of the signer
                    Mobile:
                      type: string
                      require: false
                      description: The mobile phone number of the signer
                    Iban:
                      type: string
                      description: The IBAN of the signer
                    BSN:
                      type: string
                      description: The BSN of the signer
                    SignRequestMessage:
                      required: true
                      description: The message - in plain text - of the sign request.
                      type: string
              Receivers:
                type: array
              Reference:
                type: string
              PostbackUrl:
                required: false
                type: string
              SignRequestMode:
                type: int
              DaysToExpire:
                type: int
                required: false
              SendEmailNotifications:
                type: boolean
                required: false
              Context:
                type: object
                description: Any valid json object which we will return back to you when doing a GET on the transaciton or when we send a postback.
      responses:
        '200':
          description: Details of the created transaction.
        '401':
          description: Not authorized to create a transaction.
  '/api/transaction/{transactionId}/file/{fileId}':
    put:
      description: Add a file to the transaction or overwrite an existing file with the same {fileId}
      parameters:
        - name: transactionId
          description: ID of an existing -- not yet started -- transaction
          in: path
          required: true
          type: string
        - name: fileId
          description: A unique identifier provided by you for the file. 
          in: path
          required: true
          type: string
      responses:
        '201':
          description: File succesfully created and added to the transaction
        '204':
          description: Existing file replaced within the specified transaction